let categories=[
    {
        id:1,
        name:"Bostad",
        icon:"building"
    },
    {
        id:2,
        name:"Bil",
        icon:"car"
    },
    {
        id:3,
        name:"Elektronik",
        icon:"mobile-alt"
    },
    {
        id:4,
        name:"Underhållning",
        icon:"dice"
    },
    {
        id:5,
        name:"Tjänster",
        icon:"tools"
    },
    {
        id:6,
        name:"Anställning",
        icon:"briefcase"
    }
]

let tags=[
    {
        id:1,
        name:"Lediga lägenheter"
    },
    {
        id:2,
        name:"Smartphone"
    },
    {
        id:3,
        name:"Lyxiga bilar"
    },
    {
        id:4,
        name:"Online tjänster"
    },
    {
        id:5,
        name:"Online underhållning"
    },
    {
        id:6,
        name:"Covid-19 tjänster"
    },
]

let ads=[
    {
        id:1,
        title:"2 rum lägenhet",
        price:2000,
        location:"Stockholm",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:1,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:2,
        title:"Samsung Galaxy S20",
        price:10000,
        location:"Göteborg",
        hasPicture:false,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:3,
        title:"Mercedes-Benz AMG GT R",
        price:20000,
        location:"Malmö",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:4,
        title:"IT Tjänster",
        price:5000,
        location:"Uppsala",
        hasPicture:true,
        chatActive:true,
        categoryId:5,
        tagId:4,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:5,
        title:"Hemifrån jobb",
        price:5000,
        location:"Gävle",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:6,
        title:"Poker",
        price:5000,
        location:"Umeå",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:7,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Karlshamn",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:8,
        title:"Audi R8",
        price:20000,
        location:"Borlänge",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:9,
        title:"Stor villa",
        price:10000,
        location:"Visby",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:10,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Halmstad",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:11,
        title:"Måleri",
        price:10000,
        location:"Östersund",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:12,
        title:"Volvo V40",
        price:10000,
        location:"Jönköping",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:13,
        title:"2 rum lägenhet",
        price:2000,
        location:"Skellefteå",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:1,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:14,
        title:"Samsung Galaxy S20",
        price:10000,
        location:"Piteå",
        hasPicture:false,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:15,
        title:"Mercedes-Benz AMG GT R",
        price:20000,
        location:"Luleå",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:16,
        title:"IT Tjänster",
        price:5000,
        location:"Kiruna",
        hasPicture:true,
        chatActive:true,
        categoryId:5,
        tagId:4,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:17,
        title:"Hemifrån jobb",
        price:5000,
        location:"Boden",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:18,
        title:"Poker",
        price:5000,
        location:"Ystad",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:19,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Växjö",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:20,
        title:"Audi R8",
        price:20000,
        location:"Västervik",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:21,
        title:"Stor villa",
        price:10000,
        location:"Västerås",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:22,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Värnamo",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:23,
        title:"Måleri",
        price:10000,
        location:"Varberg",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:24,
        title:"Volvo V40",
        price:10000,
        location:"Vänersborg",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:25,
        title:"2 rum lägenhet",
        price:2000,
        location:"Vallentuna",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:1,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:26,
        title:"Samsung Galaxy S20",
        price:10000,
        location:"Upplands Väsby",
        hasPicture:false,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:27,
        title:"Mercedes-Benz AMG GT R",
        price:20000,
        location:"Uddevalla",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:28,
        title:"IT Tjänster",
        price:5000,
        location:"Tumba",
        hasPicture:true,
        chatActive:true,
        categoryId:5,
        tagId:4,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:29,
        title:"Hemifrån jobb",
        price:5000,
        location:"Tullinge",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:30,
        title:"Poker",
        price:5000,
        location:"Trollhättan",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:31,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Trelleborg",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:32,
        title:"Audi R8",
        price:20000,
        location:"Täby",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:33,
        title:"Stor villa",
        price:10000,
        location:"Sundsvall",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:34,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Sundbyberg",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:35,
        title:"Måleri",
        price:10000,
        location:"Solna",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:36,
        title:"Volvo V40",
        price:10000,
        location:"Sollentuna",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:37,
        title:"2 rum lägenhet",
        price:2000,
        location:"Södertälje",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:1,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:38,
        title:"Samsung Galaxy S20",
        price:10000,
        location:"Skövde",
        hasPicture:false,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:39,
        title:"Mercedes-Benz AMG GT R",
        price:20000,
        location:"Skara",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:40,
        title:"IT Tjänster",
        price:5000,
        location:"Sandviken",
        hasPicture:true,
        chatActive:true,
        categoryId:5,
        tagId:4,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:41,
        title:"Hemifrån jobb",
        price:5000,
        location:"Råsunda",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:42,
        title:"Poker",
        price:5000,
        location:"Partille",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:43,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Östersund",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:44,
        title:"Audi R8",
        price:20000,
        location:"Östermalm",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:45,
        title:"Stor villa",
        price:10000,
        location:"Oskarshamn",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:46,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Örnsköldsvik",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:47,
        title:"Måleri",
        price:10000,
        location:"Örebro",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:48,
        title:"Volvo V40",
        price:10000,
        location:"Nyköping",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:49,
        title:"2 rum lägenhet",
        price:2000,
        location:"Norrtälje",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:1,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:50,
        title:"Samsung Galaxy S20",
        price:10000,
        location:"Norrköping",
        hasPicture:false,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:51,
        title:"Mercedes-Benz AMG GT R",
        price:20000,
        location:"Nässjö",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:52,
        title:"IT Tjänster",
        price:5000,
        location:"Nacka",
        hasPicture:true,
        chatActive:true,
        categoryId:5,
        tagId:4,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:53,
        title:"Hemifrån jobb",
        price:5000,
        location:"Motala",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:54,
        title:"Poker",
        price:5000,
        location:"Mölndal",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:55,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Märsta",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:56,
        title:"Audi R8",
        price:20000,
        location:"Lund",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:57,
        title:"Stor villa",
        price:10000,
        location:"Linköping",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:58,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Lidköping",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:59,
        title:"Måleri",
        price:10000,
        location:"Lidingö",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:60,
        title:"Volvo V40",
        price:10000,
        location:"Lerum",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:61,
        title:"2 rum lägenhet",
        price:2000,
        location:"Landskrona",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:1,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:62,
        title:"Samsung Galaxy S20",
        price:10000,
        location:"Kungsbacka",
        hasPicture:false,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:63,
        title:"Mercedes-Benz AMG GT R",
        price:20000,
        location:"Kungälv",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:64,
        title:"IT Tjänster",
        price:5000,
        location:"Kristinehamn",
        hasPicture:true,
        chatActive:true,
        categoryId:5,
        tagId:4,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:65,
        title:"Hemifrån jobb",
        price:5000,
        location:"Kristianstad",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:66,
        title:"Poker",
        price:5000,
        location:"Köping",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:67,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Katrineholm",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:68,
        title:"Audi R8",
        price:20000,
        location:"Karlstad",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:69,
        title:"Stor villa",
        price:10000,
        location:"Karlskrona",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:70,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Karlskoga",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:71,
        title:"Måleri",
        price:10000,
        location:"Karlshamn",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:72,
        title:"Volvo V40",
        price:10000,
        location:"Kalmar",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:73,
        title:"Hemifrån jobb",
        price:5000,
        location:"Jakobsberg",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:74,
        title:"Poker",
        price:5000,
        location:"Huskvarna",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:75,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Huddinge",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:76,
        title:"Audi R8",
        price:20000,
        location:"Helsingborg",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:77,
        title:"Stor villa",
        price:10000,
        location:"Hässleholm",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:78,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Härnösand",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:79,
        title:"Måleri",
        price:10000,
        location:"Haninge",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:80,
        title:"Volvo V40",
        price:10000,
        location:"Gamla Uppsala",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:81,
        title:"2 rum lägenhet",
        price:2000,
        location:"Falun",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:1,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:82,
        title:"Samsung Galaxy S20",
        price:10000,
        location:"Falköping",
        hasPicture:false,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:83,
        title:"Mercedes-Benz AMG GT R",
        price:20000,
        location:"Falkenberg",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:84,
        title:"IT Tjänster",
        price:5000,
        location:"Eslöv",
        hasPicture:true,
        chatActive:true,
        categoryId:5,
        tagId:4,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:85,
        title:"Hemifrån jobb",
        price:5000,
        location:"Eskilstuna",
        hasPicture:false,
        chatActive:false,
        categoryId:6,
        tagId:6,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:86,
        title:"Poker",
        price:5000,
        location:"Enköping",
        hasPicture:true,
        chatActive:true,
        categoryId:4,
        tagId:5,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:87,
        title:"BMW M8 Gran Coupé",
        price:20000,
        location:"Bromma",
        hasPicture:true,
        chatActive:false,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:88,
        title:"Audi R8",
        price:20000,
        location:"Borås",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:3,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:89,
        title:"Stor villa",
        price:10000,
        location:"Boo",
        hasPicture:false,
        chatActive:false,
        categoryId:1,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:90,
        title:"Iphone 12 pro max",
        price:10000,
        location:"Årsta",
        hasPicture:true,
        chatActive:true,
        categoryId:3,
        tagId:2,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:91,
        title:"Måleri",
        price:10000,
        location:"Ängelholm",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:92,
        title:"Volvo V40",
        price:10000,
        location:"Alingsås",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:93,
        title:"Måleri",
        price:10000,
        location:"Åkersberga",
        hasPicture:true,
        chatActive:false,
        categoryId:5,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
    {
        id:94,
        title:"Volvo V40",
        price:10000,
        location:"Majorna",
        hasPicture:true,
        chatActive:true,
        categoryId:2,
        tagId:0,
        imageUrl:"https://picsum.photos/200"
    },
]

export function getCategories(){
    return categories;
}

export function getTags(){
    return tags;
}

export function getAds(){
    return ads;
}